steps:
  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/ekspedisi-cloudrun/$COMMIT_SHA", "."]

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/ekspedisi-cloudrun/$COMMIT_SHA"]

  # Entrypoint, timeout and environment variables
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    timeout: 240s
    args: ["compute", "instances", "create-with-container", "my-vm-name", "--container-image", "gcr.io/$PROJECT_ID/ekspedisi-cloudrun/$COMMIT_SHA"]
