steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/ekspedisi-cloudrun:$COMMIT_SHA", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/ekspedisi-cloudrun:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "ekspedisi-cloudrun"
      - "--image"
      - "gcr.io/$PROJECT_ID/ekspedisi-cloudrun:$COMMIT_SHA"
      - "--allow-unauthenticated"
      - "--region"
      - "asia-southeast1"

images:
  - "gcr.io/$PROJECT_ID/ekspedisi-cloudrun:$COMMIT_SHA"

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ekspedisi-cloudrun:$COMMIT_SHA', "."]

  # Push Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ekspedisi-cloudrun:$COMMIT_SHA']

  # Deploy to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ekspedisi-cloudrun'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nama_image'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
